version: "3"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - "./test.txt:/usr/app/test.txt"
    ports:
      - "8080:8080"
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      - gradle
      - test

