name: Deploy Spring Service
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t poperlo/spring-server -f Dockerfile.dev .
      - run: docker run poperlo/spring-server gradle test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git"'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-spring-server
          environment_name: Dockerspringserver-env
          existing_bucket_name: elasticbeanstalk-us-east-1-557783318123
          version_label:  ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip