name: Deploy Spring Service
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t poperlo/spring-server -f Dockerfile.dev .
      - run: docker run poperlo/spring-server gradle test